---
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=50000"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
      - id: check-json
        exclude: ".vscode/tasks.json"
      - id: check-case-conflict
      - id: check-symlinks
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
        args:
          [
            "--ignore=body-is-missing,body-min-length",
            "--contrib=contrib-title-conventional-commits",
            "--msg-filename",
          ]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint
  - repo: https://github.com/barklan/git-hooks
    rev: v0.1.2
    hooks:
      - id: go-test
      - id: go-format
      - id: forbid-binary
      - id: docker-compose-check
      - id: snake-case-filenames
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.3.2
    hooks:
      - id: sqlfluff-lint
        args: ["--dialect=postgres"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.3
    hooks:
      - id: prettier
        types_or: [css, javascript, ts, vue, html, scss]
  - repo: local
    hooks:
      - id: dotenv-linter
        name: run dotenv linter
        language: docker_image
        entry: dotenvlinter/dotenv-linter --recursive
        files: \.env$
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.50.1
    hooks:
      - id: golangci-lint
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
        additional_dependencies: [flake8-eradicate, flake8-pytest-style]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-c=pyproject.toml"]
        exclude: "_test.py$|test_.*.py$"
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
