version: '3.9'

networks:
  traefik-public:
    external: false
services:
  db:
    deploy:
      placement:
        constraints:
        - node.role == manager
    environment:
      DOCKER_IMAGE_PREFIX: registry.gitlab.com/gerda_mirror/backend/
      DOCKER_REGISTRY: registry.gitlab.com/gerda_mirror/backend
      DOMAIN: hack.barklan.com
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: lqz8fgjM4JLYUPf96JxvXefXwhIhEN9hDdEXtqpAy198Fl0d
      POSTGRES_USER: sarah
      REGISTRY_PASSWORD: rdsUmNUNEKHm8Qvxfqhy
      REGISTRY_USERNAME: gitlab+deploy-token-1449716
      YANDEX_GEOCODER_API_KEY: 0695c790-ae90-407d-92cd-90eeadd9cf84
    image: registry.gitlab.com/gerda_mirror/backend/postgres:15.0
    networks:
      traefik-public: null
    ports:
    - published: 5432
      target: 5432
    volumes:
    - sarah-postgres:/var/lib/postgresql/data/pgdata:rw
  sarah:
    build:
      args:
        BUILDKIT_INLINE_CACHE: '1'
        DOCKER_IMAGE_PREFIX: registry.gitlab.com/gerda_mirror/backend/
      context: /data
      dockerfile: ./dockerfiles/sarah.dockerfile
    deploy:
      labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.sarah-http.rule=Host(`hack.barklan.com`) && (PathPrefix(`/api/`))
      - traefik.http.routers.sarah-http.entrypoints=http
      - traefik.http.routers.sarah-http.middlewares=https-redirect
      - traefik.http.routers.sarah-https.rule=Host(`hack.barklan.com`) && (PathPrefix(`/api/`))
      - traefik.http.routers.sarah-https.entrypoints=https
      - traefik.http.routers.sarah-https.tls=true
      - traefik.http.routers.sarah-https.tls.certresolver=le
      - traefik.http.services.sarah.loadbalancer.server.port=8000
      placement:
        constraints:
        - node.role == manager
    environment:
      DOCKER_IMAGE_PREFIX: registry.gitlab.com/gerda_mirror/backend/
      DOCKER_REGISTRY: registry.gitlab.com/gerda_mirror/backend
      DOMAIN: hack.barklan.com
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: lqz8fgjM4JLYUPf96JxvXefXwhIhEN9hDdEXtqpAy198Fl0d
      POSTGRES_USER: sarah
      REGISTRY_PASSWORD: rdsUmNUNEKHm8Qvxfqhy
      REGISTRY_USERNAME: gitlab+deploy-token-1449716
      YANDEX_GEOCODER_API_KEY: 0695c790-ae90-407d-92cd-90eeadd9cf84
    image: registry.gitlab.com/gerda_mirror/backend/barklan/sarah:rolling
    networks:
      traefik-public: null
    ports:
    - published: 8000
      target: 8000
  traefik:
    command:
    - --providers.docker
    - --providers.docker.watch=true
    - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
    - --providers.docker.exposedbydefault=false
    - --providers.docker.swarmmode
    - --entrypoints.http.address=:80
    - --entrypoints.https.address=:443
    - --certificatesresolvers.le.acme.email=qufiwefefwoyn@gmail.com
    - --certificatesresolvers.le.acme.storage=/certificates/acme.json
    - --certificatesresolvers.le.acme.tlschallenge=true
    - --accesslog
    - --log
    - --api
    deploy:
      labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-public-http.rule=Host(`traefik.hack.barklan.com`)
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.middlewares=https-redirect
      - traefik.http.routers.traefik-public-https.rule=Host(`traefik.hack.barklan.com`)
      - traefik.http.routers.traefik-public-https.entrypoints=https
      - traefik.http.routers.traefik-public-https.tls=true
      - traefik.http.routers.traefik-public-https.service=api@internal
      - traefik.http.routers.traefik-public-https.tls.certresolver=le
      - traefik.http.services.traefik-public.loadbalancer.server.port=8085
      placement:
        constraints:
        - node.role == manager
    environment:
      DOCKER_IMAGE_PREFIX: registry.gitlab.com/gerda_mirror/backend/
      DOCKER_REGISTRY: registry.gitlab.com/gerda_mirror/backend
      DOMAIN: hack.barklan.com
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: lqz8fgjM4JLYUPf96JxvXefXwhIhEN9hDdEXtqpAy198Fl0d
      POSTGRES_USER: sarah
      REGISTRY_PASSWORD: rdsUmNUNEKHm8Qvxfqhy
      REGISTRY_USERNAME: gitlab+deploy-token-1449716
      YANDEX_GEOCODER_API_KEY: 0695c790-ae90-407d-92cd-90eeadd9cf84
    image: registry.gitlab.com/gerda_mirror/backend/traefik:2.9.1
    networks:
      traefik-public: null
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - traefik-public-certificates:/certificates:rw
version: '3.8'
volumes:
  sarah-postgres:
    external: false
  traefik-public-certificates: {}

